#!/bin/sh
set -eu

rm -rf ~/tmp/movein
mkdir -p ~/tmp/movein
pushd ~/tmp/movein

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap cloudfoundry/tap
brew tap starkandwayne/cf
brew tap jhunt/hacks
brew install \
  bosh-cli cf-cli credhub-cli \
  safe vault spruce genesis shield gotcha osb s3 jq \
  kubectl kubernetes-helm \
  go git tcpdump tmux tmate docker mtr sipcalc socat tree watch
brew cask install virtualbox vagrant vagrant-manager \
  firefox homebrew/cask-versions/firefox-developer-edition \
  visual-studio-code iterm2 slack tunnelblick google-chrome \
  zoomus docker

popd ~/tmp/movein
rm -rf ~/tmp/movein
